# Site wide configuration

title:            Estar Pronto é Tudo            
locale:           pt_BR
url:              http://blog.gersondias.net


# Jekyll configuration

permalink:   /:categories/:title/
markdown:    kramdown
highlighter: pygments
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false


# Site owner
owner:
  name: Gerson Dias
  avatar: avatar.jpg
  bio: "Consultor ALM, desenvolvedor de softwares e sonhador. Nisso e no mais, um aprendiz"
  email: eu@gersondias.net
  disqus-shortname: 
  twitter: http://twitter.com/gersondias
  facebook: http://facebook.com/gerson1812
  google:
    plus: http://plus.google.com/+gersondias1812
    analytics: Blog GersonDias 
    verify: UA-54893505-1
    ad-client: 
    ad-slot: 
  bing-verify: 
  github: http://github.com/GersonDias
  stackoverflow: http://stackoverflow.com/users/2453793/Gerson-Dias
  linkedin: br.linkedin.com/in/gersondias/

include: [".htaccess"]
excludj: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md"]
